[profile.default]
src = 'contracts'
out = 'out'
solc_version = "0.8.19"
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
baseSepolia= "${baseSepolia_RPC_URL}"

[etherscan]
goerli = { key = "${GOERLI_SCAN_API_KEY}", url = "${GOERLI_ETHERSCAN_VERIFIER_URL}" }
optimism = { key = "${OPTIMISM_SCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}" }
baseSepolia = { key = "${baseSepolia_SCAN_API_KEY}", url = "${baseSepolia_ETHERSCAN_VERIFIER_URL}" }

[invariant]
runs = 200
depth = 20
fail_on_revert = false

[profile.lite]
optimizer = false
